// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: resume.proto

package resumeadvisor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Resumetext    string                 `protobuf:"bytes,2,opt,name=resumetext,proto3" json:"resumetext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{0}
}

func (x *ResumeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResumeRequest) GetResumetext() string {
	if x != nil {
		return x.Resumetext
	}
	return ""
}

type ResumeFeedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeFeedback) Reset() {
	*x = ResumeFeedback{}
	mi := &file_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeFeedback) ProtoMessage() {}

func (x *ResumeFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeFeedback.ProtoReflect.Descriptor instead.
func (*ResumeFeedback) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeFeedback) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_resume_proto protoreflect.FileDescriptor

const file_resume_proto_rawDesc = "" +
	"\n" +
	"\fresume.proto\x12\rresumeadvisor\"K\n" +
	"\rResumeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"resumetext\x18\x02 \x01(\tR\n" +
	"resumetext\"2\n" +
	"\x0eResumeFeedback\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions2\xb1\x01\n" +
	"\rResumeService\x12J\n" +
	"\vGetFeedback\x12\x1c.resumeadvisor.ResumeRequest\x1a\x1d.resumeadvisor.ResumeFeedback\x12T\n" +
	"\x13GetDetailedFeedback\x12\x1c.resumeadvisor.ResumeRequest\x1a\x1d.resumeadvisor.ResumeFeedback0\x01BCZAgithub.com/Sharooq-Ebrahim/ResumeAdvisor-gRPC/proto;resumeadvisorb\x06proto3"

var (
	file_resume_proto_rawDescOnce sync.Once
	file_resume_proto_rawDescData []byte
)

func file_resume_proto_rawDescGZIP() []byte {
	file_resume_proto_rawDescOnce.Do(func() {
		file_resume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resume_proto_rawDesc), len(file_resume_proto_rawDesc)))
	})
	return file_resume_proto_rawDescData
}

var file_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resume_proto_goTypes = []any{
	(*ResumeRequest)(nil),  // 0: resumeadvisor.ResumeRequest
	(*ResumeFeedback)(nil), // 1: resumeadvisor.ResumeFeedback
}
var file_resume_proto_depIdxs = []int32{
	0, // 0: resumeadvisor.ResumeService.GetFeedback:input_type -> resumeadvisor.ResumeRequest
	0, // 1: resumeadvisor.ResumeService.GetDetailedFeedback:input_type -> resumeadvisor.ResumeRequest
	1, // 2: resumeadvisor.ResumeService.GetFeedback:output_type -> resumeadvisor.ResumeFeedback
	1, // 3: resumeadvisor.ResumeService.GetDetailedFeedback:output_type -> resumeadvisor.ResumeFeedback
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resume_proto_init() }
func file_resume_proto_init() {
	if File_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resume_proto_rawDesc), len(file_resume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resume_proto_goTypes,
		DependencyIndexes: file_resume_proto_depIdxs,
		MessageInfos:      file_resume_proto_msgTypes,
	}.Build()
	File_resume_proto = out.File
	file_resume_proto_goTypes = nil
	file_resume_proto_depIdxs = nil
}
